### ISSUE TITLE
Binary incompatiblity with JOSM

### ISSUE THREAD

**Issue by don-vip** [ROTARIUANAMARIA/CADTools#1]
Hi,
If you run JOSM check-plugins ant task you will notice it currently fails with this reason:

check-plugins:
     [echo] Check of plugins binary compatibility (needs ant 1.8)
     [copy] Copying 3 resources to C:\Users\Vincent\JOSM\core\plugin-check
[as:build-signatures] Capturing signatures from C:\Users\Vincent\JOSM\core\dist\josm-custom-optimized.jar
[as:build-signatures] Capturing signatures from C:\Program Files\Java\jdk1.7.0_72\jre\lib\rt.jar
[as:build-signatures] Capturing signatures from C:\Program Files\Java\jdk1.7.0_72\jre\lib\jce.jar
[as:build-signatures] Wrote signatures for 22242 classes.
[as:check-signature] Checking unresolved references to C:\Users\Vincent\JOSM\core\plugin-check\api.sig
[as:check-signature] Ignoring the signatures from file to be checked: C:\Users\Vincent\JOSM\core\plugin-check
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/AdvancedEditorPanel.class:47: Undefined reference: void org.openstreetmap.josm.gui.tagging.TagEditorPanel.<init>(org.openstreetmap.josm.gui.tagging.TagEditorModel, org.openstreetmap.josm.gui.dialogs.properties.PresetListPanel.PresetHandler)
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:35: Undefined reference: org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority.IS_IN_STANDARD
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:35: Undefined reference: void org.openstreetmap.josm.gui.tagging.ac.AutoCompletionListItem.<init>(String, org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority)
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:36: Undefined reference: org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority.IS_IN_STANDARD
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:36: Undefined reference: void org.openstreetmap.josm.gui.tagging.ac.AutoCompletionListItem.<init>(String, org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority)
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:37: Undefined reference: org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority.IS_IN_STANDARD
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:37: Undefined reference: void org.openstreetmap.josm.gui.tagging.ac.AutoCompletionListItem.<init>(String, org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority)
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:38: Undefined reference: org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority.IS_IN_STANDARD
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/MemberRoleCellEditor.class:38: Undefined reference: void org.openstreetmap.josm.gui.tagging.ac.AutoCompletionListItem.<init>(String, org.openstreetmap.josm.gui.tagging.ac.AutoCompletionItemPritority)
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/list/TurnRestrictionCellRenderer.class:125: Undefined reference: org.openstreetmap.josm.gui.JMultilineLabel
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/list/TurnRestrictionCellRenderer.class:125: Undefined reference: void org.openstreetmap.josm.gui.JMultilineLabel.<init>(String)
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/list/TurnRestrictionCellRenderer.class:136: Undefined reference: org.openstreetmap.josm.gui.JMultilineLabel
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/list/TurnRestrictionCellRenderer.class:136: Undefined reference: void org.openstreetmap.josm.gui.JMultilineLabel.<init>(String)
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/TurnRestrictionEditor$SavingAction.class:572: Undefined reference: org.openstreetmap.josm.command.ConflictAddCommand
[as:check-signature] C:\Users\Vincent\JOSM\core\plugin-check\CADTools.jar:org/openstreetmap/josm/plugins/turnrestrictions/editor/TurnRestrictionEditor$SavingAction.class:572: Undefined reference: void org.openstreetmap.josm.command.ConflictAddCommand.<init>(org.openstreetmap.josm.gui.layer.OsmDataLayer, org.openstreetmap.josm.data.conflict.Conflict)

BUILD FAILED
C:\Users\Vincent\JOSM\core\build.xml:519: Signature errors found. Verify them and ignore them with the proper annotation if needed.

I don't know how you build your plugin jar since you don't share the source code (which I find very strange for a Github project by the way) but you must recompile your plugin to latest JOSM if you want to avoid crashes at runtime.

I also don't get it why you include turnrestrictions plugin class files. If you need this plugin at runtime, that's not the way to go. You must use the "Requires" directive in your build.xml.

See https://josm.openstreetmap.de/wiki/DevelopersGuide/DevelopingPlugins#ThemanifestfileforaJOSMplugin for reference.

Cheers,
Vincent

**Comment by don-vip** [comment]
This plugin has been banned from JOSM.

**Comment by Cetusek** [comment]
Vincent,

I was asked to repair this plugin. I see that all errors are connected with turnrestrictions. I deleted turnrestrictions.jar from lib directory, built CADTools.jar and run check-plugins ant task and there was no error from CADTools.jar. So turnrestrictions.jar is not necessary. 

Is it possible to bring this plugin back?

**Comment by don-vip** [comment]
turnrestrictions.jar is always in source code:
https://github.com/ROTARIUANAMARIA/CADTools/tree/master/lib

**Comment by Cetusek** [comment]
I did it locally on my notebook. I cannot push changes because of:

 https://github.com/ROTARIUANAMARIA/CADTools: git-receive-pack not permitted

Could you help me?

**Comment by don-vip** [comment]
did @ROTARIUANAMARIA give you write access to this repository?

**Comment by Cetusek** [comment]
Vincent,

The code and CADTools.jar are updated.

**Comment by Cetusek** [comment]
Vincent,

Are you going to include this plugin to JOSM?

**Comment by Marekkleciak** [comment]
Dear Vincent,
please add CADTools to the list.
We are waiting for that, especially because of 3D modeling.
I asked user cetusek for critical review of the bachelor work of my student, Anamaria Rotariu. Cetusek is an deeply involved soft. developer.

With best regards and thanks for your OSM contribution,
Marek

http://wiki.openstreetmap.org/wiki/User:Marek_kleciak

**Comment by don-vip** [comment]
Sorry for delay. I have removed CADTools from ban list see https://josm.openstreetmap.de/changeset/10143/josm/

Please make sure that someones maintains the plugin now. If I report another blocking issue that causes a lot of trouble for our users, and 18 months pass without any feedback from plugin maintainer, I will ban it again for good. I hope you understand we expect a minimum level of involvement from anyone who makes a JOSM plugin not hosted on OSM SVN repository.

**Comment by Marekkleciak** [comment]
Dear Vincent, 
thanks a lot! Of course, you´re right!
I have to fix some plug ins more: Enhanced Kendzi3D and dxf import: both made with my support as bachelor projects at the University Brasov. I will find new project owner for the both plugIns-
 Recently only CADTools has an new owner: User Cetusek. 
Best regards,
Marek

**Comment by don-vip** [comment]
Great! It's good to see new people taking care of old plugins :+1:
