### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Klumbumbus** [ROTARIUANAMARIA/CADTools#3]
see https://josm.openstreetmap.de/ticket/14227

**Comment by don-vip** [comment]
Can you please solve this? I remind you the plugin has already be banned once for not being maintained. If we have to ban it again it will be definitive.

**Comment by Cetusek** [comment]
As you can see no changes have been commited for 8 months. So why is the problem now?

**Comment by don-vip** [comment]
because the JOSM API evolves over time, so the plugins sometimes need to be updated. This is the case here, the plugin needs to be recompiled and its version increased.

**Comment by Cetusek** [comment]
I'll try to update this plugin. How much time do I have?

**Comment by ROTARIUANAMARIA** [comment]
Can You please take care of this?  I stopped developing Josm Plugin almost 2 year ago and I definetly don't have time to mantain something I've implemented. @centusek, You can take the author rights or whatever this involves and take care of this. 

Sent from Yahoo Mail on Android 
 
  On Thu, 23 Feb 2017 at 16:25, Vincent Privat<notifications@github.com> wrote:   
because the JOSM API evolves over time, so the plugins sometimes need to be updated. This is the case here, the plugin needs to be recompiled and its version increased.

**Comment by Cetusek** [comment]
I know you stopped it. I continued your work and I don't have time as well. But we can't let them kill this plugin ;)

**Comment by don-vip** [comment]
If I know the plugin is maintained you have all the time you need :)

**Comment by Cetusek** [comment]
The code was updated.

**Comment by don-vip** [comment]
The plugin is no longer compatible with latest JOSM, can you please release a new version before 31/12/2017?

**Comment by don-vip** [comment]
Up. I remind you we already banned this plugin in the past for being not maintained.

**Comment by don-vip** [comment]
@Cetusek do you still maintain this plugin?

**Comment by don-vip** [comment]
Seems not, I have marked the plugin as unmaintained.

**Comment by Cetusek** [comment]
Vincent, you gave me the time till the end of the year. I will try to update this plugin.

**Comment by don-vip** [comment]
OK thanks. Once you update the plugin, you'll just have to move it from the unmaintained section to the default section.

**Comment by Cetusek** [comment]
Vincent,
 
I'm sure you know what changes were done in JOSM. Could you write here what equivalents I should use for missing fields of functions?
The problem is with the class org.openstreetmap.josm.Main. It lost:
1. menu field,
2. map field,
3. getLayerManager function,
4. info function.

**Comment by don-vip** [comment]
You can read the javadoc of removed deprecated API here: https://josm.openstreetmap.de/changeset/13173/josm/
It contains the replacements for each removed API.

**Comment by Cetusek** [comment]
Thank you.
I changed the plugin code but I can't build it. Here is the log:

```
Buildfile: C:\workspace\josm\plugins\CADTools\build.xml
init:
pre-compile:
compile:
     [echo] compiling sources for C:\workspace\josm\dist\CADTools.jar ...

BUILD FAILED
C:\workspace\josm\plugins\build-common.xml:79: Class com.google.errorprone.ErrorProneAntCompilerAdapter could not be loaded because of an invalid dependency.

Total time: 1 second
```

I use Eclipse Luna Service Release 2 (4.4.2).

**Comment by don-vip** [comment]
You need `error_prone_ant.jar` from `..\..\core\tools`

**Comment by Cetusek** [comment]
The problem was with my classpath for Ant in External Tools Configuration.
What should I do to "move it from the unmaintained section to the default section"?

**Comment by Klumbumbus** [comment]
I activated it, see https://josm.openstreetmap.de/wiki/PluginsSource?action=diff&version=287
It is basically only a whitespace :)
