### ISSUE TITLE
CADTools does not work with JOSM 14253+

### ISSUE THREAD

**Issue by don-vip** [ROTARIUANAMARIA/CADTools#4]
`Main` was deprecated. It's gone in [JOSM 14253](https://josm.openstreetmap.de/changeset/14253/josm/).

`Main.parent` must be replaced by `MainApplication.getMainFrame()` (introduced in [JOSM 14140](https://josm.openstreetmap.de/changeset/14140/josm)).

Plugin must be [updated](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/jdk=JDK8/2081/warnings3Result/type.390147541/) and a new version released.

**Comment by Cetusek** [comment]
Done. I replaced `Main.parent` with `MainApplication.getMainFrame()`.

**Comment by don-vip** [comment]
Thanks for the update. The plugin is still flagged as incompatible. Did you release a new version?

**Comment by don-vip** [comment]
The jar has not been updated. Can you please make a proper GitHub release?

**Comment by Cetusek** [comment]
I increased `plugin.main.version` and `version.entry.commit.revision` in build.xml.
The jar is updated.
Should I do something more?

**Comment by don-vip** [comment]
It's fine now, thank you :)
